apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-service
  template:
    metadata:
      labels:
        app: exercise-service
    spec:
      containers:
        - name: exercise-service
          image: razvanmocica/exercise-service:latest
          ports:
            - containerPort: 8084
          #              hostPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: [ 'sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 2; done;' ]
        - name: wait-for-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z eureka 8761; do echo waiting for eureka; sleep 2; done;' ]
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;' ]
        - name: wait-for-zipkin
          image: busybox
          command: [ 'sh', '-c', 'until nc -z zipkin 9411; do echo waiting for zipkin; sleep 2; done;' ]
---
apiVersion: v1
kind: Service
metadata:
  name: exercise-service
spec:
  #  type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: exercise-service
