apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoices-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoices-service
  template:
    metadata:
      labels:
        app: invoices-service
    spec:
      containers:
        - name: invoices-service
          image: razvanmocica/invoices-service:latest
          ports:
            - containerPort: 8087
          #              hostPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: [ 'sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 2; done;' ]
        - name: wait-for-eureka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z eureka 8761; do echo waiting for eureka; sleep 2; done;' ]
        - name: wait-for-postgres-invoices
          image: busybox
          command: [ 'sh', '-c', 'until nc -z postgres-invoices 5432; do echo waiting for postgres-invoices; sleep 2; done;' ]
        - name: wait-for-rabbitmq
          image: busybox
          command: [ 'sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;' ]
        - name: wait-for-zipkin
          image: busybox
          command: [ 'sh', '-c', 'until nc -z zipkin 9411; do echo waiting for zipkin; sleep 2; done;' ]
---
apiVersion: v1
kind: Service
metadata:
  name: invoices-service
spec:
  #  type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: invoices-service
